### ISSUE TITLE
Can't resolve dependencies (twig/extensions ~1.1.0)

### ISSUE THREAD

**Issue by Pavinati** [umpirsky/Twig-Gettext-Extractor#24]
Hi there,

I was trying to install Twig-Gettext-Extractor, but i run into this problem : 

 Problem 1
   - umpirsky/twig-gettext-extractor 1.1.3 requires twig/extensions 1.0.* -> no matching package found.
   - umpirsky/twig-gettext-extractor 1.1.2 requires twig/extensions 1.0.* -> no matching package found.
   - umpirsky/twig-gettext-extractor 1.1.1 requires twig/extensions 1.0.* -> no matching package found.
   - umpirsky/twig-gettext-extractor 1.1.0 requires twig/extensions 1.0.* -> no matching package found.

my composer file ends like this

"require": {
    "twig/twig": "~1.0",
    "twig/extensions": "~1.1.0",
    "umpirsky/twig-gettext-extractor": "1.1.*"
}

strange considering the requirement are  "twig/extensions": ">=1.0,<2.0"

I'm working on windows7 and i'm not using symfhony.
Thanks again :)

**Comment by umpirsky** [comment]
Fixed in 1.1.5. See https://github.com/umpirsky/Twig-Gettext-Extractor/pull/25.

Thanks for reporting @Pavinati. :+1:
