### ISSUE TITLE
Provide a phar in the releases section

### ISSUE THREAD

**Issue by MazeChaZer** [umpirsky/Twig-Gettext-Extractor#30]
I think it would be very handy to have a standalone phar available for this tool.
I found it was very easy to create a phar of this project using [clue/phar-composer](https://github.com/clue/phar-composer). Just

```
$ wget https://github.com/clue/phar-composer/releases/download/v1.0.0/phar-composer.phar
$ php phar-composer.phar build umpirsky/twig-gettext-extractor:1.2.0
```

Note that the `phar` and `openssl` extensions have to be enabled in `php.ini`.

Edit: It's probably a good idea to include the version number in the build command

**Comment by umpirsky** [comment]
@MazeChaZer Thanks for your idea. I have good experience with [Box](http://box-project.github.io/box2/). I already use it for https://github.com/umpirsky/Symfony-Upgrade-Fixer. Works very well.

Might do same for this project.

**Comment by MazeChaZer** [comment]
Sounds great!
