### ISSUE TITLE
Doesn't work with absolute paths

### ISSUE THREAD

**Issue by hgezim** [umpirsky/Twig-Gettext-Extractor#36]
I've been trying to run this command with absolute paths in --files and it fails. This should be able to handle absolute paths, I think. Not sure how to keep it backward compatible now since you're concatenating `getcwd()` to the paths passed in.

**Comment by umpirsky** [comment]
@hgezim So, you are using it directly from CLI, not with Poedit?

It's not created with that in mind, but I guess you are free to create your own [twig-gettext-extractor](https://github.com/umpirsky/Twig-Gettext-Extractor/blob/master/twig-gettext-extractor) and reuse the rest of the project.

**Comment by hgezim** [comment]
I'm using it with gulp to update `pot` file and then merge them into `po` files. I think I found a workaround for my specific case, though. Maybe just document that path must be relative. 

Thanks for building this!

**Comment by umpirsky** [comment]
Thanks for using @hgezim! :+1:
