### ISSUE TITLE
Uncaught Twig_Error_Syntax: Unexpected token "punctuation"

### ISSUE THREAD

**Issue by bjornpost** [umpirsky/Twig-Gettext-Extractor#41]
> Fatal error: Uncaught Twig_Error_Syntax: Unexpected token "punctuation" of value "{" ("end of statement block" expected) in "path/to/template.html" at line 19. in /path/vendor/twig/twig/lib/Twig/TokenStream.php on line 87

The parsing fails on lines like:

    {% trans with {'%name%': 'Fabien'} %}Hello %name%{% endtrans %}

([src](http://symfony.com/doc/current/book/translation.html#twig-templates))

If I'm rendering the template from my application (Silex 2), there's no issue. Do I need to load an extra Twig extension in Twig-Gettext-Extension?

**Comment by umpirsky** [comment]
Yes, `{% trans with {'%name%': 'Fabien'}` is not part of twig, but [symfony/twig-bridge](https://packagist.org/packages/symfony/twig-bridge). You will need to load [TranslationExtension](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Extension/TranslationExtension.php#L52).

**Comment by bjornpost** [comment]
But that extension is loaded by default, [according to the source](https://github.com/umpirsky/Twig-Gettext-Extractor/blob/master/twig-gettext-extractor#L29)?

**Comment by umpirsky** [comment]
Hehum...in deed...

**Comment by umpirsky** [comment]
[TransTokenParser](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/TokenParser/TransTokenParser.php) does this magic, and it should be loaded by this extension...

**Comment by bjornpost** [comment]
Would you mind re-opening this issue? I will look into this. Maybe it's something that's changed between 2.7 and 3.0 (I'm testing on a local fork which updated the deps to `symfony/* ~3.0`).

**Comment by bjornpost** [comment]
Ok, what I've discovered:

 - `TranslationExtension::getFilters()` is called
 - `TranslationExtension::getTokenParsers()` is called
 - `TransTokenParser::parse()` or `TransDefaultDomainTokenParser::parse()` are never called.
 - Neither are `TranslationExtension::trans()` or `TranslationExtension::transchoice()`

Seems like it's just a matter of swapping the initialisation of `Twig_Extensions_Extension_I18n` and `TranslationExtension`. Will prepare PR.

**Comment by umpirsky** [comment]
Thanks @bjornpost!
