### ISSUE TITLE
Temporary directory location

### ISSUE THREAD

**Issue by cheplv** [umpirsky/Twig-Gettext-Extractor#44]
When you have no permissions to write into /tmp you will have an exception:

Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/tmp/cache/579886ff4a9e3/0e/96).' in /home/user/web/vendor/twig/twig/lib/Twig/Environment.php on line 1238

RuntimeException: Unable to create the cache directory (/tmp/cache/579886ff4a9e3/0e/96). in /home/user/web/vendor/twig/twig/lib/Twig/Environment.php on line 1238

**Comment by umpirsky** [comment]
@cheplv Is your twig environment set to use `/tmp`? See https://github.com/umpirsky/Twig-Gettext-Extractor/blob/master/Twig/Gettext/Extractor.php#L57 and https://github.com/umpirsky/Twig-Gettext-Extractor/blob/master/Twig/Gettext/Extractor.php#L93.
If yes, then it must have permissions to write them.

**Comment by cheplv** [comment]
Problem is here:
https://github.com/umpirsky/Twig-Gettext-Extractor/blob/master/twig-gettext-extractor#L26

I'v created pull request with appropriate changes to allow specify TMPDIR in environment

**Comment by umpirsky** [comment]
@cheplv Right, I added comment to your PR. Thanks!

**Comment by cheplv** [comment]
Moment - changed all things to simple sys_get_temp_dir() function which is preferable

**Comment by cheplv** [comment]
Now it's ok - ready to be merged :)

**Comment by umpirsky** [comment]
@cheplv Fair enough, thanks! :)

BTW, what's your `sys_get_temp_dir()` value?

**Comment by cheplv** [comment]
Currently ~/tmp (in homefolder)

P.S. When to wait for new release. Need ASAP :)

**Comment by cheplv** [comment]
Thanks for v1.2.1, maybe need to remove "v" prefix as other tag namings

**Comment by umpirsky** [comment]
@cheplv Right, thanks!

**Comment by cheplv** [comment]
Nice work. Thx!

**Comment by umpirsky** [comment]
Thank you!
