### ISSUE TITLE
Custom extension loader

### ISSUE THREAD

**Issue by drzraf** [umpirsky/Twig-Gettext-Extractor#51]
I'm trying to generate a pot file for a Drupal theme.
It uses many Drupal-specific Twig extensions.
Currently, using the phar distribution of Twig-Gettext-Extractor, it's not possible.
The parser may offer a "relax mode / ignore extensions" option.

**Comment by umpirsky** [comment]
Covered in https://github.com/umpirsky/Twig-Gettext-Extractor#custom-extensions.

**Comment by drzraf** [comment]
I cite:
https://github.com/umpirsky/Twig-Gettext-Extractor#custom-extensions.
Now you may add your custom extensions [here](https://github.com/umpirsky/Twig-Gettext-Extractor/blob/master/twig-gettext-extractor#L41)
But this is note possible when using the **phar** archive. Assuming on project modification in order to get it working is suboptimal and even unacceptable in many case.
At least a configuration option, an environment variable or an include_path trick could be used to fetch custom extensions from

**Comment by umpirsky** [comment]
Yes, not possible with phar in deed.
