### ISSUE TITLE
Twig 2.0

### ISSUE THREAD

**Issue by coolternet** [umpirsky/Twig-Gettext-Extractor#55]
not compatible with Twig 2.x

**Comment by umpirsky** [comment]
Yes, we should just update `comoser.json`. Pull requests are welcome. Thanks.

**Comment by coolternet** [comment]
What i need to change on my json ?
atm, i have it : https://fkcd.ca/sNV.png

**Comment by umpirsky** [comment]
@coolternet Not yours, we need to change https://github.com/umpirsky/Twig-Gettext-Extractor/blob/master/composer.json#L14 to support Twig 2.0.

**Comment by acelaya** [comment]
Is this already fixed?

I see the code is merged, but this is already opened

**Comment by umpirsky** [comment]
Yes, it is, closing. ;)

**Comment by acelaya** [comment]
Ok, thanks :)
